/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DeclareIndexRouteImport } from './routes/declare/index'
import { Route as DeclareArriveRouteImport } from './routes/declare/arrive'
import { Route as DeclareDepartRouteImport } from './routes/declare/depart'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DeclareDoneCodeRouteImport } from './routes/declare/done.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclareIndexRoute = DeclareIndexRouteImport.update({
  id: '/declare/',
  path: '/declare/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclareArriveRoute = DeclareArriveRouteImport.update({
  id: '/declare/arrive',
  path: '/declare/arrive',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclareDepartRoute = DeclareDepartRouteImport.update({
  id: '/declare/depart',
  path: '/declare/depart',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclareDoneCodeRoute = DeclareDoneCodeRouteImport.update({
  id: '/declare/done/$code',
  path: '/declare/done/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/declare/arrive': typeof DeclareArriveRoute
  '/declare/depart': typeof DeclareDepartRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/declare/': typeof DeclareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/declare/done/$code': typeof DeclareDoneCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/declare/arrive': typeof DeclareArriveRoute
  '/declare/depart': typeof DeclareDepartRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/declare': typeof DeclareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/declare/done/$code': typeof DeclareDoneCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/declare/arrive': typeof DeclareArriveRoute
  '/declare/depart': typeof DeclareDepartRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/declare/': typeof DeclareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/declare/done/$code': typeof DeclareDoneCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/verify'
    | '/declare/arrive'
    | '/declare/depart'
    | '/services/$slug'
    | '/declare/'
    | '/api/auth/$'
    | '/declare/done/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/verify'
    | '/declare/arrive'
    | '/declare/depart'
    | '/services/$slug'
    | '/declare'
    | '/api/auth/$'
    | '/declare/done/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/verify'
    | '/declare/arrive'
    | '/declare/depart'
    | '/services/$slug'
    | '/declare/'
    | '/api/auth/$'
    | '/declare/done/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
  DeclareArriveRoute: typeof DeclareArriveRoute
  DeclareDepartRoute: typeof DeclareDepartRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  DeclareIndexRoute: typeof DeclareIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DeclareDoneCodeRoute: typeof DeclareDoneCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declare/': {
      id: '/declare/'
      path: '/declare'
      fullPath: '/declare/'
      preLoaderRoute: typeof DeclareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declare/arrive': {
      id: '/declare/arrive'
      path: '/declare/arrive'
      fullPath: '/declare/arrive'
      preLoaderRoute: typeof DeclareArriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declare/depart': {
      id: '/declare/depart'
      path: '/declare/depart'
      fullPath: '/declare/depart'
      preLoaderRoute: typeof DeclareDepartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declare/done/$code': {
      id: '/declare/done/$code'
      path: '/declare/done/$code'
      fullPath: '/declare/done/$code'
      preLoaderRoute: typeof DeclareDoneCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
  DeclareArriveRoute: DeclareArriveRoute,
  DeclareDepartRoute: DeclareDepartRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  DeclareIndexRoute: DeclareIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DeclareDoneCodeRoute: DeclareDoneCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
